"""Add trips, items, memos tables

Revision ID: e2172e2fd5bf
Revises: 4687670c5452
Create Date: 2026-07-24 15:52:45.276838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2172e2fd5bf'
down_revision: Union[str, None] = '4687670c5452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.JSON(), nullable=False),
    sa.Column('cautions', sa.JSON(), nullable=False),
    sa.Column('baggage_summary', sa.JSON(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=True),
    sa.Column('departure_month', sa.Integer(), nullable=True),
    sa.Column('companions', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.drop_index(op.f('idx_baggage_rules_item_key'), table_name='baggage_rules')
    op.drop_table('baggage_rules')
    op.add_column('items', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('items', sa.Column('tip', sa.String(length=500), nullable=True))
    op.add_column('items', sa.Column('baggage_flag', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('checked', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_items_baggage_flag'), 'items', ['baggage_flag'], unique=False)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_checked'), 'items', ['checked'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_trip_id'), 'items', ['trip_id'], unique=False)
    op.drop_column('items', 'item_type')
    op.drop_column('items', 'weight')
    op.drop_column('items', 'notes')
    op.add_column('memos', sa.Column('trip_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_memos_id'), 'memos', ['id'], unique=False)
    op.create_index(op.f('ix_memos_trip_id'), 'memos', ['trip_id'], unique=False)
    op.drop_column('memos', 'item_id')
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_profiles_email'), table_name='profiles')
    op.drop_constraint(op.f('profiles_email_key'), 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_unique_constraint(op.f('profiles_email_key'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_profiles_email'), 'profiles', ['email'], unique=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('memos', sa.Column('item_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_memos_trip_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_id'), table_name='memos')
    op.drop_column('memos', 'trip_id')
    op.add_column('items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_trip_id'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_checked'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index(op.f('ix_items_baggage_flag'), table_name='items')
    op.alter_column('items', 'quantity',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('items', 'sort_order')
    op.drop_column('items', 'checked')
    op.drop_column('items', 'source')
    op.drop_column('items', 'baggage_flag')
    op.drop_column('items', 'tip')
    op.drop_column('items', 'category')
    op.create_table('baggage_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('carry_on_rule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('checked_rule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tips', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('baggage_rules_pkey')),
    sa.UniqueConstraint('item_key', name=op.f('baggage_rules_item_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_baggage_rules_item_key'), 'baggage_rules', ['item_key'], unique=False)
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###