"""Add nickname and password_hash to profiles

Revision ID: 4687670c5452
Revises: 20260723_1453
Create Date: 2026-07-23 19:05:13.849806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4687670c5452'
down_revision: Union[str, None] = '20260723_1453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_baggage_rules_item_key'), table_name='baggage_rules')
    op.drop_table('baggage_rules')
    op.add_column('profiles', sa.Column('nickname', sa.String(length=100), nullable=False))
    op.add_column('profiles', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'password_hash')
    op.drop_column('profiles', 'nickname')
    op.create_table('baggage_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('carry_on_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('checked_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'iata'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('baggage_rules_pkey')),
    sa.UniqueConstraint('item_key', name=op.f('baggage_rules_item_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_baggage_rules_item_key'), 'baggage_rules', ['item_key'], unique=True)
    # ### end Alembic commands ###